# Generated by Django 4.2.2 on 2023-06-28 05:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_appuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name=api.models.AppUser),
        ),
    ]
